name: dependencies
on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * 2'   # Every Tuesday at 1am

jobs:
  antq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: antq
        uses: liquidz/antq-action@main
        with:
          excludes: ''
          directories: './'
          skips: 'boot pom shadow-cljs leiningen'
